### ISSUE TITLE
GeoLite2-City.mmdb no such file

### ISSUE THREAD

**Issue by mahmoodn** [maxmind/GeoIP2-python#58]
How can I fix the following error which is related to `GeoLite2-City.mmdb` ?
```

Traceback (most recent call last):
  File "distance.py", line 15, in <module>
    reader=geoip2.database.Reader('GeoLite2-City.mmdb')
  File "/usr/lib/python2.7/site-packages/geoip2/database.py", line 86, in __init__
    self._db_reader = maxminddb.open_database(fileish, mode)
  File "/usr/lib/python2.7/site-packages/maxminddb/__init__.py", line 41, in open_database
    return maxminddb.reader.Reader(database, mode)
  File "/usr/lib/python2.7/site-packages/maxminddb/reader.py", line 52, in __init__
    with open(database, 'rb') as db_file:
IOError: [Errno 2] No such file or directory: 'GeoLite2-City.mmdb'

```

I see on the web that I have to download GeoLite2-City.mmdb. However, I can not find the download procedure? Any help?

**Comment by mahmoodn** [comment]
Excuse me. I found it https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by oschwald** [comment]
It sounds like you resolved this. I'll close the issue.
